# Generated by Django 4.1 on 2022-09-14 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('apellidos', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.IntegerField(unique=True)),
                ('nombre', models.TextField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.IntegerField()),
                ('telefono', models.CharField(max_length=50)),
                ('sector_productivo', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.TextField(unique=True)),
                ('administrador', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('fecha', models.DateField(auto_now=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaccionesFarmaceuticas.empleados')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccionesFarmaceuticas.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.TextField(unique=True)),
                ('monto', models.CharField(max_length=50)),
                ('tipo', models.TextField(unique=True)),
                ('fecha', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccionesFarmaceuticas.rol')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccionesFarmaceuticas.empresa'),
        ),
    ]
